services:
  - type: web
    name: doc-ai-scheduler-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://pushpendratri9:6ZC1fr6xZ30gWHsC@cluster0.rdsf7tb.mongodb.net/docai?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
      - key: FRONTEND_URL
        value: https://doc-ai-scheduler.onrender.com
      - key: ML_MODEL_URL
        value: https://doc-ai-scheduler-ml.onrender.com 